Feature/pta
P6-Model-Learning/Model-Learning pull request #7
Opened 2023-03-15 18:24 UTC by Sigurd00

2023-03-16 21:03 UTC, HTHNLNDN commented on src/main/java/aal/syslearner/Converter.java
> +        var bla = boards.stream().flatMap(Collection::stream).collect(Collectors.toSet());
```suggestion
        var bla = boards.stream().flatMap(Collection::stream).collect(Collectors.toSet());
```

2023-03-16 21:06 UTC, HTHNLNDN requested changes

2023-03-16 21:06 UTC, HTHNLNDN commented on src/main/java/aal/syslearner/Converter.java
> +        var bla = boards.stream().flatMap(Collection::stream).collect(Collectors.toSet());
Tænker umiddelbart et andet navn, måske bare boards?

2023-03-17 12:44 UTC, AOsnes reviewed
lgtm

2023-03-17 14:54 UTC, HTHNLNDN approved these changes

2023-03-17 17:15 UTC, merged